export const BUTTON_SUCCESS = 'CLICKED_BUTTON_SUCCESS';
export const BUTTON_REQUEST = 'CLICKED_BUTTON_REQUEST';
export const BUTTON_FAILURE = 'CLICKED_BUTTON_FAILURE';

export const LOGIN_SUCCESS = 'CLICKED_LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'CLICKED_LOGIN_REQUEST';
export const LOGIN_FAILURE = 'CLICKED_LOGIN_FAILURE';

export const LOGOUT = 'CLICKED_LOGOUT';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
