export const BUTTON_SUCCESS = 'BUTTON_SUCCESS';
export const BUTTON_REQUEST = 'BUTTON_REQUEST';
export const BUTTON_FAILURE = 'BUTTON_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
