export const CLICKED_BUTTON_SUCCESS = 'CLICKED_BUTTON_SUCCESS';
export const CLICKED_BUTTON_REQUEST = 'CLICKED_BUTTON_REQUEST';
export const CLICKED_BUTTON_FAILURE = 'CLICKED_BUTTON_FAILURE';

export const CLICKED_LOGIN_SUCCESS = 'CLICKED_LOGIN_SUCCESS';
export const CLICKED_LOGIN_REQUEST = 'CLICKED_LOGIN_REQUEST';
export const CLICKED_LOGIN_FAILURE = 'CLICKED_LOGIN_FAILURE';

export const CLICKED_LOGOUT = 'CLICKED_LOGOUT';
